### ISSUE TITLE
Experiment Setup

### ISSUE THREAD

**Issue by chengsijin0817** [ISWC-Reproducibility-Track/example#2]
Hi @pminervini, I have some questions regarding the experiment set up in your paper. Can you please clarify a bit？

In Sec.4.2 of your paper, the third paragraph, you mentioned "For all experiments, we use a cluster of machines. The crawlers are deployed on 3 machines while the created servers of the ORCA benchmark are hosted on 3 other machines." Can you please describe a bit more how did you set up the network of distributed servers?

Regarding reproducing results of the paper, in the README.md file, you indicate that the results can be simply reproduced by accessing HOBBIT and running the ORCA benchmark under the same config. If the experiment result is obtained in this way, I am wondering how do you implement the distributed server as you mentioned in the paper? In another word, do you deploy your own HOBBIT platform for this paper?

**Comment by pminervini** [comment]
Hi @chengsijin0817, this is not where you should submit issues, and I'm not the author of the paper - what's the ID of the paper you are reviewing?

**Comment by chengsijin0817** [comment]
Aha, I am sorry. I clicked the link in the email directly and created the issue here. 
Now I suppose I have submitted the issue in the correct repository (Paper_614).
Thanks for your prompt reply.
